@Library('fintech-pipeline-library') _

fintechPipeline(
    projectName: 'Identity-Service',
    sonarKey: 'fintech-identity-service',
    serviceDir: 'services/identity-service',
    subdomain: 'identity',
    internalPort: '3001'
)
