#!/bin/bash
# Security Evidence Collection Script
# Exports SonarQube Compliance Metrics for ISO 27001 Audit
# Usage: ./export_compliance.sh <SONAR_HOST> <PROJECT_KEY> <TOKEN>

SONAR_HOST="${1:-http://localhost:9000}"
PROJECT_KEY="${2:-fintech-devsecops-showcase}"
TOKEN="$3"

if [ -z "$TOKEN" ]; then
  echo "Usage: ./export_compliance.sh <SONAR_HOST> <PROJECT_KEY> <TOKEN>"
  exit 1
fi

echo "fetch compliance data for project: $PROJECT_KEY"

# Fetch Quality Gate Status
QG_STATUS=$(curl -s -u "$TOKEN": "$SONAR_HOST/api/qualitygates/project_status?projectKey=$PROJECT_KEY" | grep -o '"status":"[^"]*"' | cut -d'"' -f4)

# Fetch MQR Metrics (Security, Reliability, Maintainability Ratings)
# Note: In new SQ versions these are mapped to specific metric keys.
# security_rating: 1=A, 2=B, 3=C, 4=D, 5=E
METRICS="security_rating,reliability_rating,sqale_rating,coverage,duplicated_lines_density,ncloc"
MEASURES=$(curl -s -u "$TOKEN": "$SONAR_HOST/api/measures/component?component=$PROJECT_KEY&metricKeys=$METRICS")

echo "Generating Report..."

cat <<EOF > compliance_evidence.md
# fintech-devsecops-showcase: Security Compliance Evidence
**Date:** $(date)
**Project Key:** $PROJECT_KEY
**Quality Gate Status:** **$QG_STATUS**

## ISO 27001 / PCI-DSS Control Validation

### 1. Software Quality Ratings
| Category | Rating (1=A, 5=E) | Compliance Status |
|----------|-------------------|-------------------|
| **Security** | $(echo $MEASURES | grep -o '"metric":"security_rating","value":"[^"]*"' | cut -d'"' -f8) | $([ "$(echo $MEASURES | grep -o '"metric":"security_rating","value":"[^"]*"' | cut -d'"' -f8)" == "1.0" ] && echo "PASS" || echo "FAIL") |
| **Reliability** | $(echo $MEASURES | grep -o '"metric":"reliability_rating","value":"[^"]*"' | cut -d'"' -f8) | Check Threshold |
| **Maintainability** | $(echo $MEASURES | grep -o '"metric":"sqale_rating","value":"[^"]*"' | cut -d'"' -f8) | Check Threshold |

### 2. Code Coverage & Quality
* **Code Coverage:** $(echo $MEASURES | grep -o '"metric":"coverage","value":"[^"]*"' | cut -d'"' -f8)%
* **Duplication:** $(echo $MEASURES | grep -o '"metric":"duplicated_lines_density","value":"[^"]*"' | cut -d'"' -f8)%
* **Lines of Code:** $(echo $MEASURES | grep -o '"metric":"ncloc","value":"[^"]*"' | cut -d'"' -f8)

### 3. Certification
This document certifies that the software artifact has undergone static application security testing (SAST) and met the organization's security quality gates.

*Generated by Antigravity DevSecOps Toolkit*
EOF

echo "Report saved to compliance_evidence.md"
