sonar.projectKey=fintech-devsecops-showcase
sonar.projectName=Fintech Security Showcase - PCI-DSS MQR Restricted
sonar.projectVersion=1.0

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.spec.js,**/*.test.js,**/test/**,**/obj/**,**/coverage/**

# Multi-Quality Rule (MQR) & Compliance
# Note: Specific MQR thresholds are defined in the Quality Gate UI (Software Quality Security Rating < A)
sonar.qualitygate.wait=true

# Modules
sonar.modules=payment-gateway,ledger-api,identity-service,customer-web

# Payment Gateway (Java)
payment-gateway.sonar.projectBaseDir=services/payment-gateway
payment-gateway.sonar.sources=src/main/java
payment-gateway.sonar.java.binaries=target/classes
payment-gateway.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Ledger API (Go)
ledger-api.sonar.projectBaseDir=services/ledger-api
ledger-api.sonar.sources=.
ledger-api.sonar.go.file.suffixes=.go
ledger-api.sonar.exclusions=**/*_test.go
ledger-api.sonar.go.coverage.reportPaths=coverage.out

# Identity Service (Node.js)
identity-service.sonar.projectBaseDir=services/identity-service
identity-service.sonar.sources=.
identity-service.sonar.javascript.file.suffixes=.js,.jsx
identity-service.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Customer Web (React)
customer-web.sonar.projectBaseDir=services/customer-web
customer-web.sonar.sources=src
customer-web.sonar.javascript.file.suffixes=.js,.jsx
customer-web.sonar.javascript.lcov.reportPaths=coverage/lcov.info
