# Microcks Configuration
spring.data.mongodb.uri=mongodb://mongodb:27017/microcks
microcks.features.async-api=true
microcks.features.grpc=true
microcks.features.graphql=true
microcks.features.postman=true
microcks.features.openapi=true
# Keycloak or other auth can be added here
